# Site
name              : "elc4br4 blog"
title             : "elc4br4 blog"
description       : "Bienvenido al blog de elc4br4"
logo              : 'assets/images/elc4br4.png'
favicon           : 'assets/images/elc4br4.png'

# URL
url               : "https://elc4br4.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl           : # the subpath of your site, e.g. "/blog"
repository        : "elc4br4/elc4br4.github.io" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"

include           : ["_pages"]
google_analytics  : 'UA-xxxxxxxx-1'
disqus            : 'demowebsite'
mailchimp-list    : 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
permalink         : /:categories/:title
email             : #

# Authors
authors:
  elc4br4:
    name          : elc4br4
    display_name  : elc4br4
    gravatar      : https://es.gravatar.com/userimage/225790910/81742e7486b2345c33c12c84a73bacd9?s=250&amp;d=mm&amp;r=x
    email         : #
    twitter       : https://twitter.com/elc4br4_hacking
    description   : #"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
